import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IncogMemos",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  readonly children: React.ReactNode
}

export default async function RootLayout({
  children
}: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <body className={inter.className}>
        {children}
        <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
